title=Identifiers
date=2017-02-18
type=post
tags=identifiers, lense
status=published
~~~~~~

== Valid identifiers

In Lense, identifiers must start with a letter, followed by any combination of characters and digits. No special symbols allowed.

Identifiers are all names you use in the programs to name variables, methods, properties, fields, classes and modules


== Reserved words and keywords

Lense, like all languages, reserves some words that cannot be used as identifiers. 
Some of these reserved works are keywords, e.i. they have special meaning to the compiler. Some other are reserved to prevent use or for use in future versions.

|===
|  abstract | as | annotation | break | case | catch | class
|  continue | constructor | default | do |  else | enhancement | enum
|  export | extends | finally | for | get | if | implements 
|  implicit | import | interface | in |  is | module | native
|  new | none | out |  object | package | public | private
|  protected | return | set | super |  switch | this | throw
|  trait | try | let | var |  while | true | false
|===


